http:
    routers:
        mcp-e2e-nginx-test-39d32f8d:
            rule: PathPrefix(`/mcp/e2e-nginx-test-39d32f8d`)
            service: mcp-e2e-nginx-test-39d32f8d-service
            entryPoints:
                - web
            middlewares:
                - mcp-e2e-nginx-test-39d32f8d-stripprefix
        mcp-filesystem-instance-cb93dd87:
            rule: PathPrefix(`/mcp/filesystem-instance-cb93dd87`)
            service: mcp-filesystem-instance-cb93dd87-service
            entryPoints:
                - web
            middlewares:
                - mcp-filesystem-instance-cb93dd87-stripprefix
        mcp-manager-api:
            rule: PathPrefix(`/api/mcp`)
            service: mcp-manager-service
            entryPoints:
                - web
            middlewares:
                - mcp-api-stripprefix
        mcp-manager-catchall:
            rule: '!PathPrefix(`/mcp/`) && !PathPrefix(`/api/mcp`)'
            service: mcp-manager-service
            entryPoints:
                - web
        mcp-manager-health:
            rule: Path(`/health`)
            service: mcp-manager-service
            entryPoints:
                - web
        mcp-mcp-echo-http-d43c2606:
            rule: PathPrefix(`/mcp/mcp-echo-http-d43c2606`)
            service: mcp-mcp-echo-http-d43c2606-service
            entryPoints:
                - web
            middlewares:
                - mcp-mcp-echo-http-d43c2606-stripprefix
        mcp-mcp-echo2-e9a4959a:
            rule: PathPrefix(`/mcp/mcp-echo2-e9a4959a`)
            service: mcp-mcp-echo2-e9a4959a-service
            entryPoints:
                - web
            middlewares:
                - mcp-mcp-echo2-e9a4959a-stripprefix
        mcp-nginx-704e5037:
            rule: PathPrefix(`/mcp/nginx-704e5037`)
            service: mcp-nginx-704e5037-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-704e5037-stripprefix
        mcp-nginx-e68fb249:
            rule: PathPrefix(`/mcp/nginx-e68fb249`)
            service: mcp-nginx-e68fb249-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-e68fb249-stripprefix
        mcp-nginx-test-server-instance-d86883d1:
            rule: PathPrefix(`/mcp/nginx-test-server-instance-d86883d1`)
            service: mcp-nginx-test-server-instance-d86883d1-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-test-server-instance-d86883d1-stripprefix
        mcp-nginx-test-server-instance-fac991fe:
            rule: PathPrefix(`/mcp/nginx-test-server-instance-fac991fe`)
            service: mcp-nginx-test-server-instance-fac991fe-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-test-server-instance-fac991fe-stripprefix
        mcp-test-echo-c6c38b46:
            rule: PathPrefix(`/mcp/test-echo-c6c38b46`)
            service: mcp-test-echo-c6c38b46-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-echo-c6c38b46-stripprefix
        mcp-test-nginx-server-cb3bd69f:
            rule: PathPrefix(`/mcp/test-nginx-server-cb3bd69f`)
            service: mcp-test-nginx-server-cb3bd69f-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-nginx-server-cb3bd69f-stripprefix
        mcp-test-service-8535b145-ad538c4a:
            rule: PathPrefix(`/mcp/test-service-8535b145-ad538c4a`)
            service: mcp-test-service-8535b145-ad538c4a-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-service-8535b145-ad538c4a-stripprefix
        mcp-test-service-test-581aa3be-1b99e0e1:
            rule: PathPrefix(`/mcp/test-service-test-581aa3be-1b99e0e1`)
            service: mcp-test-service-test-581aa3be-1b99e0e1-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-service-test-581aa3be-1b99e0e1-stripprefix
    services:
        mcp-e2e-nginx-test-39d32f8d-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.3:80
        mcp-filesystem-instance-cb93dd87-service:
            loadBalancer:
                servers:
                    - url: http://127.0.0.1:8000
        mcp-manager-service:
            loadBalancer:
                servers:
                    - url: http://mcp-manager:8000
        mcp-mcp-echo-http-d43c2606-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.4:3000
        mcp-mcp-echo2-e9a4959a-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.3:3000
        mcp-nginx-704e5037-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-nginx-e68fb249-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-nginx-test-server-instance-d86883d1-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-nginx-test-server-instance-fac991fe-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-test-echo-c6c38b46-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-test-nginx-server-cb3bd69f-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:80
        mcp-test-service-8535b145-ad538c4a-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.6:80
        mcp-test-service-test-581aa3be-1b99e0e1-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.5:80
    middlewares:
        mcp-api-stripprefix:
            stripPrefix:
                prefixes:
                    - /api/mcp
                forceSlash: false
        mcp-e2e-nginx-test-39d32f8d-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/e2e-nginx-test-39d32f8d
                forceSlash: false
        mcp-filesystem-instance-cb93dd87-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/filesystem-instance-cb93dd87
                forceSlash: false
        mcp-mcp-echo-http-d43c2606-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/mcp-echo-http-d43c2606
                forceSlash: false
        mcp-mcp-echo2-e9a4959a-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/mcp-echo2-e9a4959a
                forceSlash: false
        mcp-nginx-704e5037-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-704e5037
                forceSlash: false
        mcp-nginx-e68fb249-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-e68fb249
                forceSlash: false
        mcp-nginx-test-server-instance-d86883d1-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-test-server-instance-d86883d1
                forceSlash: false
        mcp-nginx-test-server-instance-fac991fe-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-test-server-instance-fac991fe
                forceSlash: false
        mcp-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp
                forceSlash: false
        mcp-test-echo-c6c38b46-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-echo-c6c38b46
                forceSlash: false
        mcp-test-nginx-server-cb3bd69f-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-nginx-server-cb3bd69f
                forceSlash: false
        mcp-test-service-8535b145-ad538c4a-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-service-8535b145-ad538c4a
                forceSlash: false
        mcp-test-service-test-581aa3be-1b99e0e1-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-service-test-581aa3be-1b99e0e1
                forceSlash: false
